config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :profile, only: [:show, :edit, :update]
  resources :product_orders, except: [:index, :show]
  resources :product_orders, only: [:index, :show], param: :year_number, as: "date"
  resources :products, only: :index
  get :wait, to: "pages#wait"

  resources :orders do
    member do
      get :reset_status
    end
  end

  namespace :admin do
    resources :posts, only: [:edit, :update]
    resources :subcategories, only: [:index, :edit, :update, :destroy, :create]
    resources :selling_ranges
    resources :products, except: :show do
      member { get :toggle_active }
    end
    resources :categories, only: [] do
      member do
        post '/activate_products', to: 'products#activate_for'
        post '/deactivate_products', to: 'products#deactivate_for'
      end
    end

    resources :users, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
      resources :transactions, only: [:create, :destroy]
      resources :orders, only: [:create]
    end
    resources :orders, only: [:show, :edit, :update, :destroy] do
      resources :product_orders, only: [:create]
    end
    resources :product_orders, except: [:index, :show, :create]
    resources :statistics, only: [:index, :show], param: :year


    root to: 'selling_ranges#index'
  end

  root to: "pages#home"
end

app/models/selling_range.rb
class SellingRange < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :products, through: :orders
  has_many :categories, -> { distinct }, through: :products
  after_create :send_new_selling_range_email

  def quantity_of(product)
    orders.joins(:products).where('products.id = ? AND status = ?', product.id, 1).sum(:quantity)
  end

  def sales_of(product)
    orders.joins(:products).where('products.id = ? AND status = ?', product.id, 1).sum(:item_price)
  end

  def total_sales
    orders.where("status = ?", 1).sum(:total_price)
  end

  def self.next
    where('starts_at > ?', DateTime.current).order(starts_at: :asc).first
  end

  def send_new_selling_range_email
    User.where(mailable: true).each do |user|
      UserMailer.with(user: user).new_selling_range_email.deliver_later(wait_until: self.starts_at)
    end
  end
end

app/controllers/admin/selling_ranges_controller.rb
module Admin
  class SellingRangesController < Admin::ApplicationController
    before_action :set_selling_range, only: [:edit, :update, :destroy, :show]

    def index
      @selling_ranges = SellingRange.all.order(starts_at: :desc)
    end

    def new
      @selling_range = SellingRange.new
    end

    def create
      @selling_range = SellingRange.new(selling_range_params)

      if @selling_range.save
        redirect_to admin_selling_ranges_path
      else
        render :new
      end
    end

    def destroy
      @selling_range.destroy
      redirect_to admin_selling_ranges_path
    end

    def edit
    end

    def show
      @orders = Order.where(selling_range: @selling_range).validated
      @pending_orders = @selling_range.orders.includes(:user).pending.not_empty
    end

    def update
      if @selling_range.update(selling_range_params)
        redirect_to admin_selling_ranges_path
      else
        render :edit
      end
    end

    private

    def set_selling_range
      @selling_range = SellingRange.find(params[:id])
    end

    def selling_range_params
      params.require(:selling_range).permit(:starts_at, :ends_at)
    end
  end
end

app/helpers/selling_range_helper.rb
module SellingRangeHelper
end

app/views/admin/selling_ranges/_form.html.erb
<%= simple_form_for([:admin, @selling_range]) do |f| %>
  <%= f.input :starts_at, label: "Date de début"%>
  <%= f.input :ends_at, label: "Date de fin" %>
  <%= f.button :submit, "Valider", class: "btn btn-primary" %>
<% end %>

app/views/admin/selling_ranges/_harvest_by_products_tab.html.erb
<% @selling_range.categories.each do |category| %>
  <h2><%= category.name %></h2>
  <% category.products.ordered.with_order_for(@selling_range).each do |product| %>
    <%= product.name %>
    <ul>
      <% product.product_orders_for(@selling_range).each do |product_order| %>
        <li>
          <%= link_to admin_user_path(product_order.order.user) do %>
            <%= product_order.order.user.first_name %> <%= product_order.order.user.last_name %>
            <% end %> :
          <%= product_order.quantity %> <%= product_order.product.unit.pluralize(product_order.quantity) %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/admin/selling_ranges/_harvest_by_users_tab.html.erb
<% @selling_range.categories.each do |category| %>
  <h2><%= category.name %> - <%= category.selling_range_sales_for(@selling_range) %> €</h2>

  <% @orders.ordered.each do |order| %>
    <% if order.categories.include?(category) %>
      <% if order.user.mayeres == true %>
        <i class="fab fa-medium-m"></i>
      <% end %>
      <%= link_to admin_user_path(order.user) do %>
        <%= order.user.first_name %> <%= order.user.last_name %>
      <% end %>
      : <%= order.calculate_by(category) %> €
      <ul>
        <% order.product_orders.ordered.with_category(category).each do |product_order| %>
          <li><%= product_order.product.name %> -
              <%= product_order.quantity %> <%= product_order.product.unit.pluralize(product_order.quantity) %> -
              <%= product_order.item_price %> €
          </li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
<% end %>

app/views/admin/selling_ranges/_harvest_tab.html.erb
<% @selling_range.categories.each do |category| %>
  <h2><%= category.name %> - <%= number_to_currency(category.selling_range_sales_for(@selling_range)) %></h2>
  <ul>
    <% category.products.ordered.each do |product| %>
      <% if @selling_range.quantity_of(product) > 0 %>
        <li>
          <%= product.name %> :
          <%= @selling_range.quantity_of(product) %> <%= product.unit.pluralize(@selling_range.quantity_of(product)) %> -
          <%= number_to_currency(@selling_range.sales_of(product)) %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/admin/selling_ranges/edit.html.erb
<div class="container">
  <%= render 'form', selling_range: @selling_range %>
</div>

app/views/admin/selling_ranges/index.html.erb
<div class="container">

  <div class="admin-title">
    <span class="flex-title"><h1>Plages de vente</h1></span>
    <span class="flex-add"><%= button_to "Ajouter une plage de vente", new_admin_selling_range_path, method: :get, class: "btn btn-primary" %></span>
  </div>

  <table class="admin-table">
    <tr>
      <th>Plage de vente</th>
      <th>Début</th>
      <th>Fin</th>
      <th>Commandes</th>
      <th>CA total</th>
      <th>Actions</th>
    </tr>
    <% @selling_ranges.each do |selling_range| %>
      <tr data-link="<%= admin_selling_range_path(selling_range) %>">
        <td>
          <%= link_to admin_selling_range_path(selling_range) do %>
            <%= selling_range.ends_at.strftime("%Y") %> Sem <%= (selling_range.ends_at.strftime("%U")).to_i + 1 %>
          <% end %>
        </td>
        <td><%= l(selling_range.starts_at, format:"%A %d/%m/%Y") %></td>
        <td><%= l(selling_range.ends_at, format:"%A %d/%m/%Y") %></td>
        <td><%= selling_range.orders.validated.count %></td>
        <td><%= selling_range.total_sales %> €</td>
        <td>
          <%= link_to "Editer", edit_admin_selling_range_path(selling_range) %>
          <% if selling_range.orders.validated.count == 0 %>
            <%= link_to "| Supprimer", admin_selling_range_path(selling_range), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer cette plage de vente ?" } %></li>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/selling_ranges/new.html.erb
<div class="container">
  <h1>Nouvelle plage de vente</h1>
  <%= render 'form', selling_range: @selling_range %>

</div>

app/views/admin/selling_ranges/show.html.erb
<div class="container">

  <h1>Plage de vente - Semaine <%= @selling_range.ends_at.strftime("%U")%></h1>

  <% if !@pending_orders.empty? %>
  <p>Les clients suivants n'ont pas finalisé leur commande :</p>
  <ul>
    <% @pending_orders.each do |pending_order| %>
        <li><%= pending_order.user.first_name %> <%= pending_order.user.last_name %> : <%= pending_order.user.phone_number %> / <%= pending_order.user.email %></li>
      <% end %>
    <% end %>
  </ul>

  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Récoltes</a>
      <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Commandes par client</a>
      <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Commandes par produit</a>

    </div>
  </nav>

  <div class="tab-content" id="nav-tabContent">

    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <%= render 'harvest_tab' %>
    </div>

    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <%= render 'harvest_by_users_tab' %>
    </div>

    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
      <%= render 'harvest_by_products_tab' %>
    </div>
  </div>
</div>

app/views/admin/selling_ranges/update.html.erb
<h1>SellingRange#update</h1>
<p>Find me in app/views/selling_range/update.html.erb</p>