config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :profile, only: [:show, :edit, :update]
  resources :product_orders, except: [:index, :show]
  resources :product_orders, only: [:index, :show], param: :year_number, as: "date"
  resources :products, only: :index
  get :wait, to: "pages#wait"

  resources :orders do
    member do
      get :reset_status
    end
  end

  namespace :admin do
    resources :posts, only: [:edit, :update]
    resources :subcategories, only: [:index, :edit, :update, :destroy, :create]
    resources :selling_ranges
    resources :products, except: :show do
      member { get :toggle_active }
    end
    resources :categories, only: [] do
      member do
        post '/activate_products', to: 'products#activate_for'
        post '/deactivate_products', to: 'products#deactivate_for'
      end
    end

    resources :users, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
      resources :transactions, only: [:create, :destroy]
      resources :orders, only: [:create]
    end
    resources :orders, only: [:show, :edit, :update, :destroy] do
      resources :product_orders, only: [:create]
    end
    resources :product_orders, except: [:index, :show, :create]
    resources :statistics, only: [:index, :show], param: :year


    root to: 'selling_ranges#index'
  end

  root to: "pages#home"
end

app/views/shared/_contact_modal.html.erb
<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Vous avez une question ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Écrivez-nous à monts.et.legumes[arobase]gmail.com ou appelez Margaux au 07 54 35 62 12
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible alert-fix" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_mapmodal.html.erb
<div class="modal fade" id="mapModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Marché de Saint-Genis-Laval</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="market-map" class="map" style="overflow: visible"></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_mayeresModal.html.erb
<div class="modal fade" id="mayeresModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Vente à la ferme - Les Mayères</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="mayeres-map" class="map" style="overflow: visible"></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_mayeres_modal.html.erb
<div class="modal fade" id="mayeresModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Vente à la ferme - Les Mayères</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="mayeres-map" class="map" style="overflow: visible"></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-container">

    <%= link_to root_path, class: "navbar-logo" do %>
      <%= image_tag "logo.png", height: 50 %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <% if (user_signed_in? && !current_user.admin) || !user_signed_in? %>
        <%= link_to t(".sign_in", default: "Contact"), '', data: { toggle: 'modal', target: '#contactModal'} %>
      <% end %>
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <%= link_to "Admin", admin_selling_ranges_path %>
        <% end %>
        <%= link_to t(".sign_in", default: "Contact"), '', data: { toggle: 'modal', target: '#contactModal'} %>
        <%= link_to "Mes commandes", orders_path %>
        <%= link_to "Mon profil", profile_path %>
        <% if current_order.product_orders.count > 0 && current_order.status == 0 %>
          <%= link_to destroy_user_session_path, method: :delete, data: {confirm: "Attention, votre commande n'est pas validée ! Voulez-vous vraiment vous déconnecter ?"} do %>
            <i class="fas fa-power-off"></i>
          <% end %>
        <% else %>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-power-off"></i>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, data: { toggle: 'modal', target: '#logInModal'} %>
      <% end %>
    </div>
  </div>
</div>