config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :profile, only: [:show, :edit, :update]
  resources :product_orders, except: [:index, :show]
  resources :product_orders, only: [:index, :show], param: :year_number, as: "date"
  resources :products, only: :index
  get :wait, to: "pages#wait"

  resources :orders do
    member do
      get :reset_status
    end
  end

  namespace :admin do
    resources :posts, only: [:edit, :update]
    resources :subcategories, only: [:index, :edit, :update, :destroy, :create]
    resources :selling_ranges
    resources :products, except: :show do
      member { get :toggle_active }
    end
    resources :categories, only: [] do
      member do
        post '/activate_products', to: 'products#activate_for'
        post '/deactivate_products', to: 'products#deactivate_for'
      end
    end

    resources :users, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
      resources :transactions, only: [:create, :destroy]
      resources :orders, only: [:create]
    end
    resources :orders, only: [:show, :edit, :update, :destroy] do
      resources :product_orders, only: [:create]
    end
    resources :product_orders, except: [:index, :show, :create]
    resources :statistics, only: [:index, :show], param: :year


    root to: 'selling_ranges#index'
  end

  root to: "pages#home"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_orders, dependent: :destroy
  has_many :orders, through: :product_orders
  has_many :sales
  has_many :users, through: :orders
  belongs_to :category
  belongs_to :subcategory, optional: true

  validates :name, :price, :unit, presence: true

  mount_uploader :photo, PhotoUploader

  def self.active
    where(active: true)
  end

  def self.ordered
    order(name: :asc)
  end

  def self.without_subcategory
    where(subcategory: nil)
  end

  def self.with_order_for(selling_range)
    joins(:orders).where(orders: { status: 1, selling_range_id: selling_range.id }).distinct
  end

  def self.activate_for(category)
    where(category: category).each do |product|
      product.update(active: true)
    end
  end

  def self.deactivate_for(category)
    where(category: category).each do |product|
      product.update(active: false)
    end
  end

  def has_orders?
    orders.present?
  end

  def product_orders_for(selling_range)
    product_orders.joins(order: :user)
                  .where("orders.selling_range_id = ? AND orders.status = ?", selling_range.id, 1)
                  .order("users.last_name")
  end

  def general_sales_for
    product_orders.joins(:order)
                  .where("orders.status = ?", 1).sum(:item_price)
  end

  def year_sales_for(year)
    this_year = DateTime.new(year)
    next_year = DateTime.new(year + 1)
    product_orders.joins(order: :selling_range)
                  .where("selling_ranges.ends_at >= ? AND selling_ranges.ends_at < ? AND orders.status = ?", this_year, next_year, 1).sum(:item_price)
  end

  def selling_range_sales_for(selling_range)
    product_orders.joins(order: :selling_range)
                  .where("orders.selling_range_id = ? AND orders.status = ?", selling_range , 1).sum(:item_price)
  end

  def general_crops_for
    product_orders.joins(:order)
                  .where("orders.status = ?", 1).sum(:quantity)
  end

  def year_crops_for(year)
    this_year = DateTime.new(year)
    next_year = DateTime.new(year + 1)
    product_orders.joins(order: :selling_range)
                  .where("selling_ranges.ends_at >= ? AND selling_ranges.ends_at < ? AND orders.status = ?", this_year, next_year, 1)
                  .sum(:quantity)
  end

  def selling_range_crops_for(selling_range)
    product_orders.joins(order: :selling_range)
                  .where("orders.selling_range_id = ? AND orders.status = ?", selling_range , 1)
                  .sum(:quantity)
  end



end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    before_action :set_product, only: [:show, :edit, :update, :destroy, :toggle_active]
    skip_before_action :verify_authenticity_token, only: :activate_for

    def index
      @categories = Category.order(id: :asc)
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)

      if @product.subcategory.present? && @product.subcategory.category != @product.category
        flash[:alert] = "Attention, la catégorie et sous-catégorie doivent correspondre"
        render :new
      elsif @product.save
          redirect_to admin_products_path
      else
        render :new
      end
    end

    def edit
    end

    def update
      @product.assign_attributes(product_params)
      if @product.subcategory.present? && @product.subcategory.category != @product.category
        render :edit
      elsif @product.update(product_params)
          redirect_to admin_products_path
      else
        render :edit
      end
    end

    def toggle_active
      @categories = Category.order(id: :asc)
      @product.active = !@product.active
      @product.save
    end

    def deactivate_for
      @category = Category.find(params[:id])
      Product.deactivate_for(@category)
      redirect_to admin_products_path
    end

    def activate_for
      @category = Category.find(params[:id])
      Product.activate_for(@category)
      redirect_to admin_products_path
    end

    def destroy
      @product.destroy
      redirect_to admin_products_path
    end

    private

    def product_params
      params.require(:product).permit(:name, :price, :unit, :category_id, :description, :active, :photo, :subcategory_id)
    end

    def set_product
      @product = Product.find(params[:id])
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :ensure_selling_range_presence, only: :index

  def index
    redirect_to order_path(current_order) unless current_order.pending?

    @products = Product.where(active: true)
    @product_orders = current_order.product_orders
    @order = current_order
    @categories = Category.order(id: :asc)
    @post = Post.last
  end

  private

  def ensure_selling_range_presence
    unless sales_period? || current_user.admin?
      redirect_to wait_path
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product]) do |f| %>
  <%= f.input :name, label: "Nom du produit", placeholder: "Ex: Aubergines" %>
  <%= f.input :description, label: "Description" %>
  <%= f.association :category, label: "Catégorie", collection: Category.order(id: :asc) %>
  <%= f.association :subcategory, label: "Sous-catégorie - Doit appartenir à la catégorie", collection: Category.order(id: :asc), as: :grouped_select, group_method: :subcategories %>
  <%= f.input :price, label: "Prix de vente", placeholder: "3.30 - Prix au KILO ou à l'UNITE (pas aux 100G)" %>
  <%= f.input :unit, label: "Unité de vente", collection: ['100g', 'pièce', 'kilo', 'litre', 'sixaine', 'pot'] %>
  <%= f.input :active, as: :boolean, label: "Disponible cette semaine", checked_value: true, unchecked_value: false %>
  <%= f.input :photo, label: "Photo", hidden_field: :photo_cache %>
  <%= f.button :submit, "Valider", class: "btn btn-primary" %>
<% end %>

app/views/admin/products/_product_list.html.erb
<% @categories.each do |category| %>

  <h2><%= category.name %> </h2>
      <%= link_to "Activer toute la catégorie", activate_products_admin_category_path(category), method: :post %> <br>
      <%= link_to "Désactiver toute la catégorie", deactivate_products_admin_category_path(category), method: :post %>


    <% category.subcategories.ordered.each do |subcategory| %>
      <h3><%= subcategory.name %></h3>

      <% if !subcategory.products.present? %>
        <p>Pas de produit dans cette sous-catégorie</p>
      <% end %>

      <% subcategory.products.ordered.each do |product| %>
        <div class="<%= product.active ? 'product-line green-border' : 'product-line' %>" style= 'position:relative'>
          <%= link_to "", toggle_active_admin_product_path(product), remote: true, style: 'position:absolute; left:0; right:0; top:0; bottom:0'%>
          <div class="product-icon">
            <% if product.photo.present? %>
              <%= cl_image_tag product.photo, class: "avatar-bordered" %>
            <% else %>
              <div class="avatar-bordered"></div>
            <% end %>
          </div>

          <div class="product_line_responsive">

            <div class="product_info">
              <span class="product-title"> <%= product.name.capitalize %></span>
              <span class="product-price"><%= product.price %> € / <%= product.unit %></span><br>
              <span class="text-small"><%= product.description %></span>
            </div>

            <%= link_to "Editer", edit_admin_product_path(product), style: 'z-index:1000' %>
            <% if product.active? %>
              <%= link_to "Désactiver", toggle_active_admin_product_path(product), remote: true %>
            <% else %>
              <span class="activate_product"> <%= link_to "Activer", toggle_active_admin_product_path(product), remote: true %></span>
            <% end %>
            <% if !product.has_orders? %>
              <%= link_to "Supprimer", admin_product_path(product), method: :delete, style: 'z-index:1000' %>
            <% end %>
          </div>
        </div>

      <% end %>
    <% end %>

    <% if category.products.without_subcategory.present? %>
    <h3>Sans sous-catégorie</h3>
    <% end %>

    <% category.products.without_subcategory.ordered.each do |product| %>

        <div class="<%= product.active ? 'product-line green-border' : 'product-line' %>" style= 'position:relative'>
          <%= link_to "", toggle_active_admin_product_path(product), remote: true, style: 'position:absolute; left:0; right:0; top:0; bottom:0'%>
          <div class="product-icon">
            <% if product.photo.present? %>
              <%= cl_image_tag product.photo, class: "avatar-bordered" %>
            <% else %>
              <div class="avatar-bordered"></div>
            <% end %>
          </div>

          <div class="product_line_responsive">

            <div class="product_info">
              <span class="product-title"> <%= product.name.capitalize %></span>
              <span class="product-price"><%= product.price %> € / <%= product.unit %></span><br>
              <span class="text-small"><%= product.description %></span>
            </div>

            <%= link_to "Editer", edit_admin_product_path(product), style: 'z-index:1000' %>
            <% if product.active? %>
              <%= link_to "Désactiver", toggle_active_admin_product_path(product), remote: true %>
            <% else %>
              <span class="activate_product"> <%= link_to "Activer", toggle_active_admin_product_path(product), remote: true %></span>
            <% end %>
            <% if !product.has_orders? %>
              <%= link_to "Supprimer", admin_product_path(product), method: :delete, style: 'z-index:1000'  %>
            <% end %>
          </div>
        </div>


    <% end %>
<% end %>

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="card_form">
    <h1>Modifier le produit</h1>
    <%= render 'form', product: @product %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">

  <div id="products-list">
    <div class="admin-title">
      <span class="flex-title"><h1>Liste des produits</h1></span>
      <span class="flex-add"><%= button_to "Ajouter un produit", new_admin_product_path, method: :get, class: 'btn btn-primary' %></span>
    </div>
    <%= render 'product_list' %>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="card_form">
    <h1>Ajouter un produit</h1>
    <%= render 'form', product: @product %>
  </div>
</div>

app/views/admin/products/toggle_active.js.erb
var productsList = document.querySelector('#products-list');
productsList.innerHTML = "<%= j render 'product_list' %>";