config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :profile, only: [:show, :edit, :update]
  resources :product_orders, except: [:index, :show]
  resources :product_orders, only: [:index, :show], param: :year_number, as: "date"
  resources :products, only: :index
  get :wait, to: "pages#wait"

  resources :orders do
    member do
      get :reset_status
    end
  end

  namespace :admin do
    resources :posts, only: [:edit, :update]
    resources :subcategories, only: [:index, :edit, :update, :destroy, :create]
    resources :selling_ranges
    resources :products, except: :show do
      member { get :toggle_active }
    end
    resources :categories, only: [] do
      member do
        post '/activate_products', to: 'products#activate_for'
        post '/deactivate_products', to: 'products#deactivate_for'
      end
    end

    resources :users, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
      resources :transactions, only: [:create, :destroy]
      resources :orders, only: [:create]
    end
    resources :orders, only: [:show, :edit, :update, :destroy] do
      resources :product_orders, only: [:create]
    end
    resources :product_orders, except: [:index, :show, :create]
    resources :statistics, only: [:index, :show], param: :year


    root to: 'selling_ranges#index'
  end

  root to: "pages#home"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :orders, dependent: :destroy
  has_many :product_orders, through: :orders
  has_many :transactions

  validates_presence_of :first_name
  validates_presence_of :last_name

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy, :orderindex, :new_order]

    def index
      @users = User.all.order(:admin, :last_name)
    end

    def show
      @transaction = Transaction.new
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to admin_users_path
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path
      else
        render :edit
      end
    end

    def destroy
      @user.destroy
      redirect_to admin_users_path
    end

    private

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :phone_number, :mayeres, :admin, :tab, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for([:admin, @user]) do |f| %>
  <%= f.input :first_name, label: 'Prénom', error: 'Username is mandatory, please specify one' %>
  <%= f.input :last_name, label: 'Nom de famille' %>
  <%= f.input :phone_number, placeholder: '0123456789' %>
  <%= f.input :email, placeholder: 'utilisateur@nomdedomaine.com' %>
  <% if with_password %>
    <%= f.input :password %>
  <% end %>
  <%= f.input :mayeres %>
  <%= f.input :tab %>
  <%= f.input :admin %>
  <%= f.button :submit, "Valider", class: "btn btn-primary" %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container">
  <h1>Modifier le profil de <%= @user.first_name %> <%= @user.last_name %></h1>

  <%= render 'form', with_password: false %>
</div>

app/views/admin/users/index.html.erb
<div class="container">

  <div class="admin-title">
    <span class="flex-title"><h1> <%= @users.count %> clients</h1></span>
    <span class="flex-add"><%= button_to "Créer un client", new_admin_user_path, method: :get, class: "btn btn-primary" %></span>

  </div>

  <table class="admin-table">
    <tr>
      <th>Nom</th>
      <th>Email</th>
      <th>Tél</th>
      <th>Commandes</th>
      <% if current_selling_range %>
        <th></th>
      <% end %>
      <th></th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td>
          <% if user.mayeres? %>
            <i class="fab fa-medium-m"></i>
          <% end %>
          <%= link_to "#{user.first_name.capitalize} #{user.last_name.capitalize}", admin_user_path(user) %>
        </td>
        <td><%= user.email %></td>
        <td><%= user.phone_number %></td>
        <td class="inline-flex"><%= user.orders.validated.count %>
        <% if current_selling_range %>
          -  <%= simple_form_for([:admin, user, Order.new]) do |f| %>
                <%= f.submit("Créer", class: "btn btn-link") %>
              <% end %>
        <% end %>
        </td>

        <td>
          <% if user.orders.validated.count == 0 && user.transactions.count ==  0 %>
            <%= link_to admin_user_path(user), method: :delete do %>
              <i class="fas fa-trash-alt fa-green"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>

</div>

app/views/admin/users/new.html.erb
<div class="container">
  <h1>Créer un nouveau client</h1>

  <%= render 'form', with_password: true %>
</div>

app/views/admin/users/show.html.erb
<div class="container">

  <h1> <span class="flex-title">Profil de <%= @user.first_name %> <%= @user.last_name %></span>
       <span class="flex-add"><%= link_to "Editer le profil", edit_admin_user_path(@user) %></span>
  </h1>

  <p><i class="far fa-envelope fa-gray"></i> <%= @user.email %><p>
  <p><i class="fas fa-phone fa-gray"></i> <%= @user.phone_number %></p>

  <h2>Commandes effectuées</h2>
  <% if @user.orders.validated.present? %>
    <ul>
      <% @user.orders.validated.each do |order| %>
        <li>
          <%= link_to admin_order_path(order) do %>
            Semaine <%= order.selling_range.ends_at.strftime('%W') %>
          <% end %> -
          Montant <%= order.total_price %> €
          <%= link_to "Supprimer", admin_order_path(order), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer cette commande ?" }  %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>Aucune commande pour le moment</p>
  <% end %>

  <h2>Ardoise : <%= @user.tab %> €</h2>

  <%= simple_form_for([:admin, @user, @transaction]) do |f| %>
    Ajouter :
    <%= f.hidden_field :add, value: true %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.input :amount, label: false, placeholder: "€" %>
    <%= f.submit "Valider", class: "btn btn-primary btn-margin-right" %>
  <% end %>

  <%= simple_form_for([:admin, @user, @transaction]) do |f| %>
    Soustraire :
    <%= f.hidden_field :add, value: false %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.input :amount, label: false, placeholder: "€" %>
    <%= f.submit "Valider", class: "btn btn-primary" %>
  <% end %>

  <% if @user.transactions.blank? %>
    <p>Aucune transaction</p>
  <% else %>
    <table>
      <tr>
        <th>Date</th>
        <th>Transaction</th>
        <th>Montant</th>
        <th></th>
      </tr>
      <% @user.transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.created_at.strftime("%d-%m-%Y") %></td>
          <% if transaction.add == true %> <td>Ajout</td> <% else %> <td>Retrait</td><% end %>
          <td><%= transaction.amount %> €</td>
          <td><%= link_to "Supprimer", admin_user_transaction_path(@user, transaction), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer cette transaction ?" } %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>